__prefix___nginx:
    build: ./nginx/
    ports:
        - 5011:5011
    links:
        - __prefix___php
    volumes_from:
        - __prefix___app
    restart: unless-stopped

__prefix___php:
    build: ./php/
    expose:
        - 9000
    ports:
        - "5012:22"
    links:
        - __prefix___mysql
    volumes_from:
        - __prefix___app
    restart: unless-stopped

__prefix___app:
    image: busybox
    volumes:
        - ./www/html:/var/www/html:z
        - ./data:/var/hook
    restart: unless-stopped
    command: "tail -f /var/hook/file.txt"

__prefix___mysql:
    image: mysql:5.7
    volumes_from:
        - __prefix___data
    environment:
        MYSQL_ROOT_PASSWORD: "secret_root_password"
        MYSQL_DATABASE: __dbname__
        MYSQL_USER: __dbname__
        MYSQL_PASSWORD: "secret_db_password"
    restart: unless-stopped

__prefix___data:
    image: busybox
    volumes:
        - ./mysql:/var/lib/mysql
        - ./data:/var/hook
    restart: unless-stopped
    command: "tail -f /var/hook/file.txt"

__prefix___phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 5013:80
    links:
        - __prefix___mysql
    environment:
        PMA_HOST: __prefix___mysql
    restart: unless-stopped

__prefix___ftp:
    image: atmoz/sftp
    ports:
        - "5014:22"
    volumes:
        - ./www/html:/home/__prefix__/html
    restart: unless-stopped
    command: __prefix__:__secret_sftp_password__:33:33
